[tool.poetry]
name = "crack"
version = "0.1.0"
description = ""
authors = ["wmymz <wmymz@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12"
crypto-plus = "*"
asarpy = "*"
requests = "^2.31.0"
pysocks = "^1.7.1"
grequests = "^0.7.0"
beautifulsoup4 = "^4.12.3"
lxml = "^5.1.1"
websockets = "^12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
priority = "default"
