[tool.poetry]
name = "crack"
version = "0.1.0"
description = ""
authors = ["wmymz <wmymz@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12"
crypto-plus = "^0.1.2"


[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
